feat: add option to return reason when is_alive returns false
emqx/influxdb-client-erl pull request #44
Opened 2023-01-31 14:19 UTC by olcai

We want the caller to is_alive to be able to log the reason for why is_alive returns false. This is now possible by calling influx:is_alive(Client, true).

2023-01-31 14:21 UTC, olcai commented
I'm not sure what the release procedures are for this repo. Please tell me what else I need to do.

2023-02-02 15:03 UTC, zhongwencool commented on src/influxdb_http.erl
> +        logger:error("[InfluxDB] is alive: ~0p ~0p ~0p", [E, R, S]),
```suggestion
        logger:error("[InfluxDB] is broken: ~0p ~0p ~0p", [E, R, S]),
```

2023-02-08 18:34 UTC, olcai commented on src/influxdb_http.erl
> +        logger:error("[InfluxDB] is alive: ~0p ~0p ~0p", [E, R, S]),
I have now clarified that it is the function `is_alive` that's intended here, not that it is actually alive.

2023-02-09 14:06 UTC, zmstone commented on src/influxdb_http.erl
>          false
maybe just return `{false, #{exception => E, reason => R, stacktrace => S}}` here.
caller should log this `false` reason.

2023-02-09 14:28 UTC, zmstone commented on src/influxdb_http.erl
>          false
maybe add a `log_or_return(#{exception => E, reason => R, stacktrace => S}, ReturnReason)`.

2023-02-09 19:41 UTC, olcai commented on src/influxdb_http.erl
>          false
Yes, that is smart. I have implemented it now.

2023-02-16 16:03 UTC, thalesmg reviewed
LGTM

For the release, I think we'll need to bump the version here in `app.src`, and will probably need a couple new `.appup.src` entries.

One tip is to create a temporary tag at this branch's HEAD (e.g.: `1.1.8-erik0`), use that version in EMQX and either run `scripts/update-appup.sh emqx-enterprise` locally or create a PR with that version and CI will help.

After the appup is ironed out, then we tag `master` with the true version.

2023-02-16 17:27 UTC, zmstone approved these changes

2023-02-16 17:28 UTC, zmstone requested changes
Sorry, please update .app.src and .appup.src as @thalesmg suggested.

2023-02-22 15:46 UTC, olcai commented on src/influxdb.app.src
> +              {vsn,"1.1.8"},
Okay, I've put it back to `git` again.

2023-02-22 16:03 UTC, thalesmg approved these changes

2023-02-23 07:57 UTC, merged